# Generated by Django 5.1.3 on 2024-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_publ_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=10)),
            ],
        ),
    ]
