# Generated by Django 5.1.3 on 2024-11-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_ejem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejem',
        ),
    ]
