# Generated by Django 5.1.3 on 2024-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('curso', models.CharField(max_length=200)),
            ],
        ),
    ]
