# Generated by Django 5.1.3 on 2024-11-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=200)),
                ('fingr', models.DateField()),
            ],
        ),
    ]
