# Generated by Django 5.1.3 on 2024-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
                ('ciclo', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('materias', models.ManyToManyField(related_name='estmat', to='app1.materia')),
            ],
        ),
    ]
